services:
  postgres:
    image: postgres:13.5
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: discord-clone
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      discord-network:

networks:
  discord-network:
    driver: bridge

volumes:
  postgres:
    driver: local
